---
title: "previewactivity4"
author: "Kyle Bistrain"
format:
  html:
    self-contained: true
    mainfont: Times New Roman
    code-fold: true
    code-summary: "show the code"
editor: visual
execute:
 echo: true
 message: false
 warning: false
---

```{r}
#warning: false

library(tidyverse)
library(readxl)
library(ggplot2)
library(DT)

```

1\.

```{r}
#warning: false
military <- readxl::read_xlsx( 
  here::here("supporting_artifacts",
             "learning targets", 
             "gov_spending_per_capita.xlsx"
             ),
  sheet = "Share of Govt. spending", 
  skip = 7, 
  n_max = 191
                        )

                      




```

2\.

```{r}
military_clean <- military |> 
  mutate(across(.cols = everything(), .fns = ~na_if(x = ., y = ". .")),
         across(.cols = everything(), .fns = ~na_if(x = ., y = "xxx"))
         )

military_clean <- military_clean |> 
  mutate(across(.cols = `1988`:`2019`, .fns = ~as.numeric(x = .)))
military_clean |> 
  datatable()
  

```

The `echo: false` option disables the printing of code (only output is displayed).

3\.

```{r}
cont_region <- read_xlsx(here::here("supporting_artifacts", 
                                    "learning targets", 
                                    "gov_spending_per_capita.xlsx"
                                    ), 
                         sheet = "Regional totals", 
                         skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")

cont_region |> 
  datatable()

```

4\.

```{r}
military_join_1 <- military_clean |> 
  anti_join(cont_region, c("Country" = "Region") )
military_join_1 |> 
  datatable()
```

5\.

```{r}
military_join_2 <- military_join_1 |> 
  pivot_longer(`1988`:`2019`,
               values_to = "Spending",
               names_to = "Year")
military_join_2 |> 
  datatable()
```

6\.

```{r}
ggplot(data = military_join_2,
       mapping = aes(x = Spending, 
               y = Year
                     )) + 
         geom_boxplot()
       
```
