---
title: "Final Grade Reflection"
author: "Kyle Bistrain"
format: 
  html:
      self-contained: true
editor: visual
---

In STAT 331, I think that I earned an B+ to A-.

Grading Requirements

**Learning Targets**
WD-1 practiceactivity4.qmd \# 1 Reading in xlsx file using here and lab 7 #1 reading in csv using here function.

WD-2 Lab 3 #7 using the select function.

WD-3 Lab 3 #5 using the distinct function and Lab 9 #2 using the filter function.

WD-4 Lab 3 #4 using mutate to modify variable types and Lab 7 \# 2 for modifying existing variables.

WD-5 cerealpreview.qmd #4 and #5 right join

WD-6 Lab 4 \# 2 using semi_join and anti_join 

WD-7 Lab 4 #7 using pivot_longer and Lab 9 #7 pivot_wider

R-1 Lab 9 is a professional looking quarto document.

R-2 Lab 9  is well documented and tidy code

R-3 Lab 7 #5 uses stopifnot to make sure the function is robust and has the proper input.

DVS-1 Lab 5 #2  has boxplots with jitters and Lab #5 use geom_line

DVS-2 Lab 9 #3 I used a geom_text label to label each bar

DVS-3 Lab 7 #6 I made two graphs side by side with grid.arrange

DVS-4 Lab 7 #1 I computed the sum of NA's for each variable

DVS-5 Lab 4 #6 I created a summary with multiple variables

DVS-6 Challenge 9 #10 my summary is clear to the viewer

DVS-7 Challenge 9 #10 I should creativity in my table construction

PE-1  Lab 9 #10

PE-2 Lab 8 #5 I wrote a function to reduce repetition.

PE-3 Lab 8 #6 I use the map_chr function.

PE-4 Lab 8# 3 all the functions in this code chunk display modern tools.

DSM-1 regression.qmd #8

DSM-2 preview9.qmd #1

**Revising your Thinking**

Over the course of this class, I submitted a revision for every single assignment that I received an incomplete for. I also made sure to write a thorough reflection to really sum up what I learned from making revisions. I also did not submit lab 8 and challenge 8 to canvas, but I did complete the assignment for the portfolio. Additionally, I think that writing the reflection helped me figure out what concepts I was struggling on.

**Extending Thinking:**

I also tried my hardest to push myself on every challenge assignment. Every opportunity I had, I chose to complete the most difficult challenge. One challenge that I had the most trouble with was figuring out how to use the latex language. I struggled for an hour or so to figure out the right syntax. I am glad that I learned how to make an equation with the latex language because I can use this in the future in implement functions and other complex math symbols into my R code. Another challenge assignment that I had fun with was the lab 2 challenge because I got to customize my color palate. Another challenge assignment that I did well on was Challenge assignment 3. I used proper statistical language to

**Collaborative Group Member:**

 As far as group work, I feel that I am a contributing team member because I collaborated well with my team over the course of the quarter. We also had each others contacts in case we have trouble on practice activities. I really enjoyed the group working environment. I also made to sure to prepare for class and always stay on top of the new material. Also, occasionally group members from other groups join our table. and It was nice to collaborate with other classmates. I also like that our group is very friendly and we are not afraid or shy to collaborate.

**Peer Review:**

This is the one area that I think I could improve on. If I completed my assignments earlier I could have completed more peer reviews. Since I turned in some assignments late, canvas did not assign me a peer to review. I did not peer review people's code every week when I was behind on assignments. During the weeks that I submitted labs and challenges on time I gave people code reviews. Also, when I gave people code reviews I tried to give kind, but honest advice to help classmates improve their assignments.

**Additional Area for grading:**

Im not sure if this counts for anything in your grade consideration, but I was present to class every day during the quarter except for the one Thursday that I was traveling for Nationals. I made it a priority to make it class and try my absolute hardest!

\

