---
title: "My Growth as a Data Scientist"
format: 
  html:
    self-contained: true
execute: 
  echo: true
  message: false
  warning: false
---

Over this course, I have made strides in becoming a data scientist, but I want to zoom in on data visualization in data tables and graphs and cleansing data. At the beginning of the quarter, I had no clue how to store data in R and was unsure of what type of data type to use. I quickly learned about data frames and their usefulness, but in several projects, I would display my data with a tibble. Tibbles are not visually pleasing and frequently do not display the whole data frame. I finally learned how to make tables visually pleasing in challenge 9. I used the kable function from the knitr package which allowed me to make presentable tables. I also learned the datatable function from the DT package, which displays an interactive data table when you render an HTML file. I think these skills are vital to my growth as a data scientist because now I can display data on an HTML file which I can use in presentations or professionally show peers my findings.

Another aspect of data visualization that I have improved is my graphing skills using ggplot. At the beginning of the quarter, I made basic plots using ggplot without modifying labels and legends. Throughout the quarter, I worked on making my graphs more informative and visually pleasing. In Challenge 7, I displayed my graphing skills by recoding facet labels and making a graph encompassing four variables and a facet grid. I also showed my ability to use different graph types(using ggplot) in lab 5 and incorporate several different layers in one graph. These core skills are crucial for data scientists because they need to be able to convey their findings to a larger audience clearly and concisely.

Finally, another skill that data scientists need to utilize is data cleaning and modifying data frames. At the beginning of the quarter, I understood the basic principles of filtering data, but I never understood how to implement the principles in R. Soon after starting this course, I learned how to modify variable types and use functions like pivot_wider and pivot_longer. These tools are vital for data scientists because it allows you to take raw data and modify it to analyze the variables that you want to visualize. The beauty of learning these fundamental skills is that once you learn how to modify variables, you can apply the same skills to any data set of your choosing. I demonstrated proficiency in data cleaning throughout lab 4. I deployed pivot_wider to summarize the price of avocados with a region in each row and organic or conventional in each column. The pivot_wider transformed the variable type to make the tibble one column wider. Additionally, in lab 4, I used functions like slice_max() to select cells in the tibble that I want to be on the HTML rendering. After taking this course, I am more familiar with what being a data scientist entails and how they transform raw data into conclusions and visualizations that someone with a non-technical background can comprehend.
